// placeholder
export type Policy = {}

export const defaultPolicies: Policy[] = [
    {
        'comment': 'gridOperator policy variable',
        'id': 'pol444002',
        'name': null,
        'original_id': 444002,
        'parameter': 'Grid_MS_congestion_allowance_level_kW',
        'resourcetype': 'Policy',
        'unit': 'kW',
        'value': '0',
    },
    {
        'comment': 'gridOperator policy value',
        'id': 'pol444005',
        'name': null,
        'original_id': 444005,
        'parameter': 'Grid_MS_congestion_pricing_consumption_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'null',
        'value': 'TRUE',
    },
    {
        'comment': 'gridOperator policy value',
        'id': 'pol444006',
        'name': null,
        'original_id': 444006,
        'parameter': 'Grid_MS_congestion_pricing_production_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'null',
        'value': 'TRUE',
    },
    {
        'comment': 'Fixed_electricity_price',
        'id': 'pol444007',
        'name': null,
        'original_id': 444007,
        'parameter': 'Fixed_electricity_price_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'EUR p kWh',
        'value': '0.21',
    },
    {
        'comment': 'Fixed_heat_price',
        'id': 'pol444008',
        'name': null,
        'original_id': 444008,
        'parameter': 'Fixed_heat_price_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'EUR p kWh',
        'value': '0.1',
    },
    {
        'comment': 'Fixed_methane_price',
        'id': 'pol444009',
        'name': null,
        'original_id': 444009,
        'parameter': 'Fixed_methane_price_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'EUR p kWh',
        'value': '0.05',
    },
    {
        'comment': 'Fixed_hydrogen_price',
        'id': 'pol444010',
        'name': null,
        'original_id': 444010,
        'parameter': 'Fixed_hydrogen_price_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'EUR p kWh',
        'value': '0.3',
    },
    {
        'comment': 'p_variableElectricityPriceOverNational_eurpkWh',
        'id': 'pol444011',
        'name': null,
        'original_id': 444011,
        'parameter': 'Energy_supplier_electricity_price_margin_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'fr',
        'value': '0.17',
    },
    {
        'comment': 'p_fixedFeedinTariff_eurpkWh',
        'id': 'pol444012',
        'name': null,
        'original_id': 444012,
        'parameter': 'Fixed_electricity_feed_in_tariff_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'EUR_pKWh',
        'value': '0.1',
    },
    {
        'comment': 'Fixed_diesel_price',
        'id': 'pol444013',
        'name': null,
        'original_id': 444013,
        'parameter': 'Fixed_diesel_price_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'EUR_pKWh',
        'value': '0.2',
    },
    {
        'comment': 'Time_buffer_for_spread_charging, Integer value',
        'id': 'pol444014',
        'name': null,
        'original_id': 444014,
        'parameter': 'Time_buffer_for_spread_charging_min',
        'resourcetype': 'Policy',
        'unit': 'minutes',
        'value': '60',
    },
    {
        'comment': 'switch for salderen',
        'id': 'pol444015',
        'name': null,
        'original_id': 444015,
        'parameter': 'Salderen',
        'resourcetype': 'Policy',
        'unit': 'boolean',
        'value': 'false',
    },
    {
        'comment': 'power level at which capacity pricing kicks in',
        'id': 'pol444016',
        'name': null,
        'original_id': 444016,
        'parameter': 'Capacitypricing_households_kW',
        'resourcetype': 'Policy',
        'unit': 'int',
        'value': '5',
    },
    {
        'comment': 'capacity price value for households',
        'id': 'pol444017',
        'name': null,
        'original_id': 444017,
        'parameter': 'Capacitypricing_households_eur',
        'resourcetype': 'Policy',
        'unit': 'float',
        'value': '0.5',
    },
    {
        'comment': 'gridOperator policy value',
        'id': 'pol444003',
        'name': null,
        'original_id': 444003,
        'parameter': 'Grid_MS_congestion_price_eurpkWh',
        'resourcetype': 'Policy',
        'unit': 'eurpkWh',
        'value': '0.5',
    },
    {
        'comment': 'COP value where the hybrid heatpump switches from heatpump to gas for space heating. Based on ETM value',
        'id': 'pol520100',
        'name': 'p_hybridHeatPumpCOPThreshold',
        'original_id': 520100,
        'parameter': 'p_hybridHeatPumpCOPThreshold',
        'resourcetype': 'Policy',
        'unit': null,
        'value': '2.6',
    },
    {
        'comment': 'gridOperator policy value',
        'id': 'pol444004',
        'name': null,
        'original_id': 444004,
        'parameter': 'Grid_MS_congestion_threshold_fr',
        'resourcetype': 'Policy',
        'unit': 'fr',
        'value': '0.5',
    },
]
